{% set name = "pythonji" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythonji-{{ version }}.tar.gz
  sha256: 6d757578095ace4f31019e36ebed46e657741c1d355100dfa3eaa3060b160a49

build:
  entry_points:
    - pythonji = pythonji.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit
    - pip
  run:
    - python >={{ python_min }}
    - emoji

test:
  imports:
    - pythonji
  commands:
    - pip check
    - pythonji --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gahjelle/pythonji
  summary: 🐍 - Write Python with Emojis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
