schema_version: 1

context:
  name: pythonji
  version: 0.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pythonji-${{ version }}.tar.gz
  sha256: 6d757578095ace4f31019e36ebed46e657741c1d355100dfa3eaa3060b160a49

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pythonji = pythonji.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - flit
    - pip
  run:
    - python >=${{ python_min }}
    - emoji

tests:
  - python:
      imports:
        - pythonji
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - pythonji --help

about:
  summary: 🐍 - Write Python with Emojis
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/gahjelle/pythonji

extra:
  recipe-maintainers:
    - pavelzw
